### ISSUE TITLE
RF model building height from OSM data

### ISSUE THREAD

**Issue by jetschny** [FAIRiCUBE/resource-metadata#1]
### Name of resource

testcase for estimating building height from openstreet map data using random forest model

### ID

shouldthisnotbeassignedbysystem?

### Description

testcase for estimating building height from openstreet map data using random forest model.

how different should the description be from the name? from the size of the textbox, the user might feel encouraged to provide a lot of input in both (or duplicate)?

### Main category

ML

### Other category

A

### Pubblication date

selection above A or B? do I win a porsche if I choose gate B?

24.04.2027

### Objective

regression

### Platform

Local Jupyter Notebook

### Framework

Scikit-learn

### Architecture

random-forest

### Approach

supervised

### Algorithm

Random-Forest-Classifier

### Processor

cpu

### OS

linux

### Keyword

building height
openstreet map 
random forest model

### Input data

does not exist yet as the input is local...

### Characteristics of input data

Open Street Map data

### Biases and ethical aspects

no issues here, the machine is always right

### Output data

does not exist yet as the input is local...

### Characteristics of output data

building height information asociated to OSM buildings

### Performance

good, craches often, reason unknown.

### Conditions for access and use

MIT

**Comment by cozzolinoac11** [comment]
Hi @jetschny ,
Below are some considerations/replies to your questions:

-     Yes, "ID" value will be assigned by system (when it will be ready).
-     In "Other category" the codelist is not yet available, so we left the example values A and B. As this field is not mandatory, it can always be left empty. We could  add an indication to the field to specify that the codelist is not yet available (and remove this comment when codelist will be available).
-     The "Example" in this case could be the used Jupyter Notebook (when it will be ready to be loaded).
-     "Input data" in this case could be the OpenStreetMap link from which the data was downloaded.
-     "Characteristics of input data" in this case could be the description of OpenStreetMap data used (e.g. which layer)
-     "Output data" in this case could be the model through which you make predictions (when it will be ready to be loaded) and "Characteristics of output data" will for example provide some information on format and structure of the data expected by the model to obtain a prediction. In this regard, maybe could be good to add a comment for this field to make more explicit what we expect?

**Comment by KathiSchleidt** [comment]
@jetschny : what's status on this issue? Have you made progress, or still struggling, or just forgot? ;)
