### ISSUE TITLE
Architecture codelist - replace 'cnn' with 'dnn'

### ISSUE THREAD

**Issue by jetschny** [FAIRiCUBE/resource-metadata#2]
# Change proposal description

## Codelist name

Architecture

## Codelist value

cnn

## Codelist value description

why only Convolutional neural networks?

## Issue faced

too specfic

## Change proposer

dnn
deep neural networks

**Comment by cozzolinoac11** [comment]
Hi @jetschny, I agree with your observation. 
I have already edited the value by replacing "cnn" with "dnn" to make it less specific. Thank you!

**Comment by cozzolinoac11** [comment]
Hi @jetschny, the value 'cnn' was again added to the codelist of the architecture field along with other architectures to better specify the type of neural network. Therefore, now both 'dnn' and 'cnn' and other architectures are in the codelist.

**Comment by KathiSchleidt** [comment]
@jetschny 
Can this issue be closed as resolved?

**Comment by cozzolinoac11** [comment]
In my opinion, it makes sense to provide as many details as possible when specifying the architecture used and its algorithm because this helps in understanding the resource.
Now, both values ('cnn' and 'dnn') are present in the codelist of the 'Architecture' field, so we can use either the more specific or the less specific one depending on the situation.

**Comment by KathiSchleidt** [comment]
Maybe I'm just stupid, but if the catalog also wants to address non-ML-experts, maybe full text in place of acronyms would help? CNN I can now parse, DNN I'm still lost.

Remember that we also want domain scientists like Martin to be able to find something useful!

**Comment by cozzolinoac11** [comment]
@KathiSchleidt I agree with you and we can use both the name and the acronym. For example 'CNN - Convolutional-Neural-Network' instead of just the CNN acronym. What do you think?

**Comment by KathiSchleidt** [comment]
Perfect! Best of both worlds!!! :)

**Comment by cozzolinoac11** [comment]
I have just updated the codelist using the structure <acronym - full name>. Specifically, I updated the values of the fields 'architecture' and 'algorithm'.
